target_sources(DigitQt
    PRIVATE
        ApertureSamples.h
        ApertureSamples.cpp
        Measurement.h
        Measurement.cpp
        ShapeCollectionAccess.h
        AutoSeedPlacement.h
        AutoSeedPlacement.cpp
        ImagePadding.h
        ImagePadding.cpp
        NumberedFringeLine.h
        FringeOrdering.h
        FringeOrdering.cpp
        FringeEdgeExtrapolation.h
        FringeEdgeExtrapolation.cpp
        PhaseMap.h
        ModalAnalysisResult.h
        ModalAnalysisResult.h
        ModalAnalysisReportData.h
        ModalAnalysisReportData.cpp
        ModalFitMethod.h
        PolynomialBasis.h
        SequentialSereginResult.h
)

add_subdirectory(commands)
add_subdirectory(pipeline)
